# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ENBDPixabay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ENBDPixabay
  pod 'SnapKit'
  pod 'FBSnapshotTestCase'
  
  target 'ENBDPixabayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
